package com.example.auth.Controller;

import com.example.auth.Domain.Account;
import com.example.auth.Domain.Token;
import com.example.auth.Repository.AccountRepository;
import com.example.auth.jwt.JwtTokenUtil;
import com.example.auth.service.JwtUserDetailsService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.boot.ApplicationRunner;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.core.ValueOperations;
import org.springframework.security.access.annotation.Secured;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.userdetails.UserDetails;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;

import javax.transaction.Transactional;
import java.util.HashMap;
import java.util.Map;


@RestController
@CrossOrigin
@RequestMapping // This means URL's start with /demo (after Application path)
public class MainController {
    private Logger logger = LoggerFactory.getLogger(ApplicationRunner.class);

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private AccountRepository accountRepository;

    @Autowired
    RedisTemplate<String, Object> redisTemplate;

    @Autowired
    private PasswordEncoder bcryptEncoder;

    @Autowired
    private JwtTokenUtil jwtTokenUtil;

    @Autowired
    private JwtUserDetailsService userDetailsService;

    @Autowired
    private AuthenticationManager am;


    @RequestMapping(value = "/newuser/login", method = RequestMethod.POST)
    public Map<String, Object> login(@RequestBody Map<String, String> m) throws Exception {
        logger.info("test input username: " + m.get("username") + ", password: " + m.get("password"));
        am.authenticate(new UsernamePasswordAuthenticationToken(m.get("username"), m.get("password")));

        final UserDetails userDetails = userDetailsService.loadUserByUsername(m.get("username"));
        final String token = jwtTokenUtil.generateAccessToken(userDetails);
        logger.info("test input username: " + m.get("username") + ", password: " + m.get("password"));

        /*
        Token tok = new Token();
        tok.setUsername(m.get("username"));
        tok.setToken(token);

        //generate Token and save in redis
        ValueOperations<String, Object> vop = redisTemplate.opsForValue();
        vop.set(m.get("username"), tok);
        */
        logger.info("generated token: " + token);
        Map<String, Object> map = new HashMap<>();
        map.put("token", token);
        return map;
    }


    @PostMapping(path="/newuser/add") // Map ONLY POST Requests
    public Map<String, Object> addNewUser (@RequestBody Account account) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        String un = account.getUsername();
        Map<String, Object> map = new HashMap<>();
        System.out.println("회원가입요청 아이디: "+un + "비번: " + account.getPassword());
        if (accountRepository.findByUsername(un) == null) {
            account.setUsername(un);
            account.setEmail(account.getEmail());
            if (un.equals("admin")) {
                account.setRole("ROLE_ADMIN");
            } else {
                account.setRole("ROLE_USER");
            }

            account.setPassword(bcryptEncoder.encode(account.getPassword()));
            map.put("success", true);
            accountRepository.save(account);
            return map;
        } else {
            map.put("success", false);
            map.put("message", "duplicated username");
        }
        return map;
    }



    @PostMapping(path="/newuser/checkemail")
    public boolean checkEmail (@RequestBody Map<String, String> m) {
        System.out.println("이메일체크 요청 이메일: " + m.get("email"));
        if (accountRepository.findByEmail(m.get("email")) == null) return true;
        else return false;
    }

    @Transactional
    @PostMapping(path="/deleteuser")
    public void deleteUser (@RequestBody Map<String, String> m) {
        logger.info("delete user: " + m.get("username"));
        Long result = accountRepository.deleteByUsername(m.get("username"));
        logger.info("delete result: " + result);
    }

    @Secured("ROLE_ADMIN")
    @GetMapping(path="/getusers")
    public Iterable<Account> getAllUsers() {
        return accountRepository.findAll();
    }

    @Secured("ROLE_ADMIN")
    @GetMapping(path="/hello")
    public String hello() {
        return "hello~";
    }

    @GetMapping(path="/admin/test")
    public String admin() {
        return "admin";
    }

    @CrossOrigin(origins = {"http://localhost:3000"})
    @Secured("ROLE_USER")
    @GetMapping(path="/onlynormal")
    public String onlyNormal() {
        return "안녕 일반 유저";
    }
}